### ISSUE TITLE
Non static matrix creation

### ISSUE THREAD

**Issue by ryanwebster90** [vlfeat/autonn#14]
I'm under the intention that matrix creation operators (e.g. Layer.randn) should be non static, because they are often used with size. For example
```Matlab
x = Input() ;
b = ones(size(x,2),1);
y = x*b;
```
Modifying functions to accommodate this reduces the drop in usability of autonn.

**Comment by jotaf98** [comment]
Hi, yes that's a good point. In fact I've been finding the liberal use of static methods to be a hindrance in various situations lately.

The only reason they're static is for encapsulation, but they'd best be treated as simple functions. On the other hand it's nice to use a standard name (randn) instead of something made up (in order not to clash with the original randn). Any ideas?

**Comment by jotaf98** [comment]
Hi, yes that's a good point. In fact I've been finding the liberal use of static methods to be a hindrance in various situations lately. I think it would be best to replace them with simple overloads, that are not static.

There was a use case for them, but lately I've integrated enough options that they're not needed anymore, namely the Var class. So I'll see about changing them back.

**Comment by jotaf98** [comment]
Done!
