### ISSUE TITLE
Shakespeare LSTM demo error 

### ISSUE THREAD

**Issue by Tar12** [vlfeat/autonn#20]
"The class Layer has no Constant property or Static method named 'zeros'."
in Line 57.

Thanks!

**Comment by jotaf98** [comment]
Just fixed it, thanks for catching that!

**Comment by Tar12** [comment]
Thanks for the quick reply, the code is really neat, but it would be nice if there was an example for LSTM regression with arbitrary input (i.e. features of D dimensions). For instance, regress a continuous variable given a history of examples/targets. The Shakespeare example is complex, and the minimal only takes 1D binary features.

**Comment by jotaf98** [comment]
Yes, the Shakespeare example kinda does that. It performs classification where the class label is "nextChar". If you make getBatch return a continuous variable instead of a class, and change the loss from vl_nnloss (classification) to vl_nnpdist (regression), it will do that.

Remember that getImdb and getBatch are specific to this Shakespeare text. You can (and should ;) ) replace them with your own dataset for your regression task. Everything else remains the same :)
