### ISSUE TITLE
Debug architecture filter size mismatch

### ISSUE THREAD

**Issue by wajahat57** [vlfeat/autonn#23]
I have created an architecture with autoNN to train.
There is some mismatch between the filter sizes. Therefore, I get the following error:
******************************
_### FILTERS are larger than the DATA (including padding).

Error in Net/eval (line 95)
[out{:}] = layer.func(args{:}) ;

Error in cnn_train_autonn>processEpoch (line 329)
net.eval(inputs, 'normal', params.derOutputs, s ~= 1) ;_
******************************
How can I find out where in the network this mismatch is?

**Comment by jotaf98** [comment]
Before running the network, run "dbstop if error" in the command window. Then, when the error happens you'll be right in the middle of the network evaluation loop in debug mode. You can type "layer" to see which layer is running, and "args" to see the arguments that are being passed to the function that's throwing an error.

Note that this is only slightly clunky because the error is in the convolution, which is a MEX file. If you have an error in an M-file, "dbstop if error" will show you the debug context for that function, which is easier to debug. Let me know if you run into any trouble.
