### ISSUE TITLE
Derivative Selecting for Multiple Output : Objective Error  

### ISSUE THREAD

**Issue by ncalik** [vlfeat/autonn#28]
Also I have another question..
We can determine "objective" and "error"  by  using  vl_nnloss
How does AutoNN select  "objective" loss for backpropagation?

**Comment by jotaf98** [comment]
Hi, by default all the losses you include when creating a compiled network (Net) are backpropagated:

```
objective = vl_nnloss(predictions, labels, 'loss', 'softmaxlog') ;
error = vl_nnloss(predictions, labels, 'loss', 'classerror') ;
net = Net(objective, error);
```

The error will not backprop any derivatives though because it's non-differentiable, so only the objective (which is differentiable) affects the result.

You can also override the derivatives of individual outputs by specifying the derOutputs option in cnn_train_autonn or when calling net.eval().

Hope that helps!

**Comment by ncalik** [comment]
derOutputs is ok !!
many thanks

---------------------
*Nurullah ÇALIK*

2018-02-11 16:34 GMT+03:00 Joao Henriques <notifications@github.com>:
